# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\bilal\workspace\DesignSheets\ui_loginwin.ui'
#
# Created: Sat Sep 23 17:47:43 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_loginWin(object):
    def setupUi(self, loginWin):
        loginWin.setObjectName("loginWin")
        loginWin.resize(1024, 768)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(loginWin.sizePolicy().hasHeightForWidth())
        loginWin.setSizePolicy(sizePolicy)
        loginWin.setMinimumSize(QtCore.QSize(1024, 768))
        loginWin.setSizeIncrement(QtCore.QSize(100, 100))
        self.centralwidget = QtGui.QWidget(loginWin)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setMaximumSize(QtCore.QSize(1024, 750))
        self.frame.setSizeIncrement(QtCore.QSize(0, 100))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtGui.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(40, 120, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(40, 160, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.uname = QtGui.QLineEdit(self.frame)
        self.uname.setGeometry(QtCore.QRect(140, 118, 120, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.uname.setFont(font)
        self.uname.setMaxLength(30)
        self.uname.setPlaceholderText("")
        self.uname.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.uname.setObjectName("uname")
        self.pwd = QtGui.QLineEdit(self.frame)
        self.pwd.setGeometry(QtCore.QRect(140, 157, 120, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.pwd.setFont(font)
        self.pwd.setMaxLength(10)
        self.pwd.setEchoMode(QtGui.QLineEdit.Password)
        self.pwd.setObjectName("pwd")
        self.line = QtGui.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(310, 0, 20, 1028))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMinimumSize(QtCore.QSize(20, 750))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.line.setFont(font)
        self.line.setFrameShadow(QtGui.QFrame.Raised)
        self.line.setLineWidth(1)
        self.line.setMidLineWidth(0)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.login_btn = QtGui.QPushButton(self.frame)
        self.login_btn.setGeometry(QtCore.QRect(145, 200, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.login_btn.setFont(font)
        self.login_btn.setCheckable(False)
        self.login_btn.setChecked(False)
        self.login_btn.setAutoRepeat(False)
        self.login_btn.setAutoDefault(False)
        self.login_btn.setDefault(False)
        self.login_btn.setFlat(False)
        self.login_btn.setObjectName("login_btn")
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        loginWin.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(loginWin)
        self.statusbar.setInputMethodHints(QtCore.Qt.ImhNone)
        self.statusbar.setObjectName("statusbar")
        loginWin.setStatusBar(self.statusbar)

        self.retranslateUi(loginWin)
        QtCore.QMetaObject.connectSlotsByName(loginWin)

    def retranslateUi(self, loginWin):
        loginWin.setWindowTitle(QtGui.QApplication.translate("loginWin", "LeGrandPita POS", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("loginWin", "Username:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("loginWin", "Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.login_btn.setText(QtGui.QApplication.translate("loginWin", "Login", None, QtGui.QApplication.UnicodeUTF8))




